sudo: required
dist: bionic
language: generic

install:
  - cd third-party && ./build_third_party.sh && cd -
  - mkdir -p build && cd build
  - cmake .. && cmake --build . --target all

notifications:
  email:
    on_success: never
    on_failure: always
script:
  - cd build
  - ctest --verbose
