sudo: required
dist: bionic
language: cpp

install:
  - cd third-party && ./build_third_party.sh && cd -
  - mkdir -p build && cd build
  - cmake .. && cmake --build . --target all
script:
  - pwd
  - ctest --verbose
notifications:
  email:
    on_success: never
    on_failure: always
