sudo: required
dist: bionic
language: cpp

install:
  - cd third-party && ./build_third_party.sh && cd -
  - mkdir -p build && cd build
  - cmake -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target all
script:
  - export GTEST_COLOR=1
  - ctest --output-on-failure
notifications:
  email:
    on_success: never
    on_failure: always
